# Generated by Django 4.1.3 on 2022-12-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='day_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
