# Generated by Django 4.0.4 on 2022-12-19 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_attendance_facility_alter_attendance_shift_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='shared_with',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='user',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='note',
        ),
        migrations.AddField(
            model_name='profile',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.facilities'),
        ),
        migrations.AddField(
            model_name='shift',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.facilities'),
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.DeleteModel(
            name='Notes',
        ),
    ]
