# Generated by Django 4.0.4 on 2022-12-20 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_facilities_facility'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_updated',
            field=models.BooleanField(default=False),
        ),
    ]
