# Generated by Django 4.1.3 on 2022-12-21 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_profile_is_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='clock_in_time',
            field=models.TimeField(blank=True, default='00:00', null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='clock_out_time',
            field=models.TimeField(blank=True, default='00:00', null=True),
        ),
    ]
